### ISSUE TITLE
Cannot connect to/disconnect from any WiFi network, due to ifdown & ifup not being avaliable on ArchLinux(Raspberry Pi)

### ISSUE THREAD

**Issue by kv1dr** [rockymeza/wifi#51]
Ifup and ifdown is not avaliable on ArchLinux, at least on Raspberry Pi. Since they are not avaliable I can't connect to or disconnect from any WiFi. I made a script to call 'ip link set $1 down' for ifdown, so disconnecting now works, but I can't do that for ifdown, since 'ip' command doesn't have '-o MAC:ADDRESS' and other switches. Can you somehow implemet connecting and disconnecting using 'ip' command or something? Thanks

**Comment by Develoman** [comment]
Hi @rockymeza  @kv1dr ,
I have the same need #69 
please indicate any update of this bug, in latest version. 
Thanks

**Comment by osteth** [comment]
I am getting this error an believe I am having the same iss

`Traceback (most recent call last):
  File "sniff-wifi.py", line 27, in <module>
    scheme.activate()
  File "/usr/local/lib/python2.7/dist-packages/wifi/scheme.py", line 172, in activate
    subprocess.check_output(['/sbin/ifdown', self.interface], stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/sbin/ifdown', 'wlo1']' returned non-zero exit status 1
`
this happens when runnign wifi by itself as well as when using it as a library.

**Comment by Totalbug92** [comment]
Any updates on this? @rockymeza

**Comment by ahmedAlmasri** [comment]
+1 any update ?
