### ISSUE TITLE
Wifi module not works on mac yosemite

### ISSUE THREAD

**Issue by cristianchaparroa** [rockymeza/wifi#57]
Hello, I'm try to do a hello work with you module, but not works, I installed the wifi module like:
`pip install wifi`
Then when I try to do whatever with your module, for example `wifi scan` I get the following problem:
```
Traceback (most recent call last):
  File "/usr/local/bin/wifi", line 202, in <module>
    args.func(args)
  File "/usr/local/bin/wifi", line 51, in scan_command
    print_table([[cell.signal, cell.ssid, 'protected' if cell.encrypted else 'unprotected'] for cell in Cell.all(args.interface)])
  File "/usr/local/lib/python2.7/site-packages/wifi/scan.py", line 29, in all
    stderr=subprocess.STDOUT)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
how could I fix it?

**Comment by rockymeza** [comment]
Hi @cristianchaparroa,

Thank you for your interest in the wifi library. It currently only supports linux.

It makes extensive use of the linux wireless-tools libraries and tools and I don't know if there are similar tools available on mac.

I apologize for the inconvenience. I would of course be very glad to accept pull requests to add support for mac, but I don't know about the feasibility of it.

**Comment by cristianchaparroa** [comment]
I this moment I can suggest , `airport` and `networksetup` utilities from osx
