### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by JPaulMora** [rockymeza/wifi#67]
Terminal Output: Fresh install of wifi on OS X 10.10.3 (python 2.7)
`````
$ wifi scan
Traceback (most recent call last):
  File "/usr/local/bin/wifi", line 202, in <module>
    args.func(args)
  File "/usr/local/bin/wifi", line 51, in scan_command
    print_table([[cell.signal, cell.ssid, 'protected' if cell.encrypted else 'unprotected'] for cell in Cell.all(args.interface)])
  File "/usr/local/lib/python2.7/site-packages/wifi/scan.py", line 29, in all
    stderr=subprocess.STDOUT)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
`````

**Comment by rockymeza** [comment]
Hi,

The wifi library is for Linux only at the moment. Sorry!

-rocky
2015年6月1日 下午11:28于 "John M" <notifications@github.com>写道：
