### ISSUE TITLE
scan command error

### ISSUE THREAD

**Issue by luweijie007** [rockymeza/wifi#93]
hi ,thanks your tools.
I has some problem with it, i hope you can give me some help 

  File "/usr/bin/wifi", line 202, in <module>
    args.func(args)
  File "/usr/bin/wifi", line 51, in scan_command
    print_table([[cell.signal, cell.ssid, 'protected' if cell.encrypted else 'unprotected'] for cell in Cell.all(args.interface)])
  File "/usr/lib/python2.7/site-packages/wifi/scan.py", line 39, in all
    stderr=subprocess.STDOUT)
  File "/usr/lib64/python2.7/subprocess.py", line 568, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by rockymeza** [comment]
What operating system are you using?
What command did you run?

**Comment by luweijie007** [comment]
i run :wifi scan

**Comment by rockymeza** [comment]
what operating system are you using?

**Comment by luweijie007** [comment]
centos7 
thanks your answer

**Comment by rockymeza** [comment]
right now wifi only works on debian-based distributions. :(

**Comment by luweijie007** [comment]
ok i see, hope you can port this tools to centos in future!
thanks again!

**Comment by rockymeza** [comment]
I hope so too!

**Comment by rackmount** [comment]
it doesn't work on my pi, which is debian-based also.
thanks

**Comment by jjuu** [comment]
Same to me, debian 8.

(wifi)jjuu@debian:~$ wifi scan
Traceback (most recent call last):
  File "/home/jjuu/pyenv/wifi/bin/wifi", line 202, in <module>
    args.func(args)
  File "/home/jjuu/pyenv/wifi/bin/wifi", line 51, in scan_command
    print_table([[cell.signal, cell.ssid, 'protected' if cell.encrypted else 'unprotected'] for cell in Cell.all(args.interface)])
  File "/home/jjuu/pyenv/wifi/local/lib/python2.7/site-packages/wifi/scan.py", line 39, in all
    stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by jjuu** [comment]
I install wireless-tools to fix it. It due to lack of /sbin/iwlist command.

**Comment by rackmount** [comment]
Your problem is not same as mine, I have installed wireless-tools.


Raymond
