### ISSUE TITLE
the problem for ver 0.3.8

### ISSUE THREAD

**Issue by rackmount** [rockymeza/wifi#95]
Hi, Rock,
I installed wifi by pip successful, but when I run wifi or wifi scan command, the error is same and as below:
Traceback (most recent call last):
  File "/usr/local/bin/wifi", line 202, in <module>
    args.func(args)
  File "/usr/local/bin/wifi", line 51, in scan_command
    print_table([[cell.signal, cell.ssid, 'protected' if cell.encrypted else 'unprotected'] for cell in Cell.all(args.interface)])
  File "/usr/local/lib/python2.7/dist-packages/wifi/scan.py", line 44, in all
    cells = map(Cell.from_string, cells_re.split(iwlist_scan)[1:])
  File "/usr/local/lib/python2.7/dist-packages/wifi/scan.py", line 54, in from_string
    return normalize(cell_string)
  File "/usr/local/lib/python2.7/dist-packages/wifi/scan.py", line 137, in normalize
    while lines[0].startswith(' ' * 10):
IndexError: list index out of range
 but wifi  --help, works fine.

**Comment by rockymeza** [comment]
Hi!

Which os/distro are you using?

Thanks,
-rocky
2016年3月30日 上午12:28於 "rackmount" <notifications@github.com>寫道：

**Comment by rockymeza** [comment]
Ok I guess you are on your pi. Let me look into it this weekend.

-rocky
2016年4月1日 上午6:58於 "Rocky Meza" <rockymeza@gmail.com>寫道：

**Comment by rockymeza** [comment]
what is the output of `sudo /sbin/iwlist wlan0 scan`?

**Comment by rackmount** [comment]
HI,Rocky,
Sorry for the late reply.
Yes, you are right, I'm using it on a pi.

Raymond

**Comment by rackmount** [comment]
It works fine to show all Essids.

Raymond

**Comment by rockymeza** [comment]
@rackmount, can you paste in the output of `sudo /sbin/iwlist wlan0 scan` please?

**Comment by rackmount** [comment]
wlan0     Scan completed :
          Cell 01 - Address: C4:6E:1F:B3:91:52
                    ESSID:"CSBearings"
                    Mode:Managed
                    Frequency:2.422 GHz (Channel 3)
                    Quality:4/5  Signal level:-66 dBm  Noise level:-92 dBm
                    IE: IEEE 802.11i/WPA2 Version 1
                        Group Cipher : CCMP
                        Pairwise Ciphers (1) : CCMP
                        Authentication Suites (1) : PSK
                    IE: Unknown:
DD9C0050F204104A0001101044000102103B0001031047001054504C696E6B53636F70C46E1FB391521021000754502D4C494E4B10230009544C2D57523130343310240003322E301042001473636F7270696F6E4334364531464233393135321054000800060050F204000110110019576972656C65737320526F7574657220544C2D575231303433100800022008103C0001011049000600372A000120
                    IE: WPA Version 1
                        Group Cipher : CCMP
                        Pairwise Ciphers (1) : CCMP
                        Authentication Suites (1) : PSK
                    Encryption key:on
                    Bit Rates:1 Mb/s; 2 Mb/s; 5.5 Mb/s; 11 Mb/s; 6 Mb/s
                              9 Mb/s; 12 Mb/s; 18 Mb/s; 24 Mb/s; 36 Mb/s
                              48 Mb/s; 54 Mb/s
          Cell 02 - Address: 28:C6:8E:C5:B0:69
                    ESSID:"YMI-NETGEAR"
                    Mode:Managed
                    Frequency:2.412 GHz (Channel 1)
                    Quality:5/5  Signal level:-57 dBm  Noise level:-92 dBm
                    IE: IEEE 802.11i/WPA2 Version 1
                        Group Cipher : CCMP
                        Pairwise Ciphers (1) : CCMP
                        Authentication Suites (1) : PSK
                    IE: Unknown:
DD1D0050F204104A0001101044000102103C0001011049000600372A000120
                    Encryption key:on
                    Bit Rates:1 Mb/s; 2 Mb/s; 5.5 Mb/s; 11 Mb/s; 6 Mb/s
                              9 Mb/s; 12 Mb/s; 18 Mb/s; 24 Mb/s; 36 Mb/s
                              48 Mb/s; 54 Mb/s
          Cell 03 - Address: 00:1C:C2:1C:E3:EE
                    ESSID:"IDriveWiFi-E3EE"
                    Mode:Managed
                    Frequency:2.437 GHz (Channel 6)
                    Quality:2/5  Signal level:-73 dBm  Noise level:-92 dBm
                    IE: IEEE 802.11i/WPA2 Version 1
                        Group Cipher : TKIP
                        Pairwise Ciphers (2) : TKIP CCMP
                        Authentication Suites (1) : PSK
                    IE: WPA Version 1
                        Group Cipher : TKIP
                        Pairwise Ciphers (2) : TKIP CCMP
                        Authentication Suites (1) : PSK
                    Encryption key:on
                    Bit Rates:1 Mb/s; 2 Mb/s; 5.5 Mb/s; 11 Mb/s; 9 Mb/s
                              18 Mb/s; 36 Mb/s; 54 Mb/s; 6 Mb/s; 12 Mb/s
                              24 Mb/s; 48 Mb/s
          Cell 04 - Address: 18:1B:EB:E3:73:67
                    ESSID:"\x00\x00\x00\x00\x00"
                    Mode:Managed
                    Frequency:2.437 GHz (Channel 6)
                    Quality:5/5  Signal level:-45 dBm  Noise level:-92 dBm
                    IE: IEEE 802.11i/WPA2 Version 1
                        Group Cipher : TKIP
                        Pairwise Ciphers (2) : CCMP TKIP
                        Authentication Suites (1) : PSK
                    IE: WPA Version 1
                        Group Cipher : TKIP
                        Pairwise Ciphers (2) : CCMP TKIP
                        Authentication Suites (1) : PSK
                    Encryption key:on
                    Bit Rates:1 Mb/s; 2 Mb/s; 5.5 Mb/s; 11 Mb/s; 18 Mb/s
                              24 Mb/s; 36 Mb/s; 54 Mb/s; 6 Mb/s; 9 Mb/s
                              12 Mb/s; 48 Mb/s
          Cell 05 - Address: 98:FC:11:A8:07:CD
                    ESSID:"CSbearings"
                    Mode:Managed
                    Frequency:2.462 GHz (Channel 11)
                    Quality:5/5  Signal level:-57 dBm  Noise level:-92 dBm
                    IE: IEEE 802.11i/WPA2 Version 1
                        Group Cipher : TKIP
                        Pairwise Ciphers (2) : CCMP TKIP
                        Authentication Suites (1) : PSK
                    IE: Unknown:
DD8C0050F204104A00011010440001021041000100103B00010310470010D2CC9B6BFFDB40FDAFABEE9D1EEDB9DF10210012436973636F2D4C696E6B7379732C204C4C4310230017576972656C6573732D4E2041636365737320506F696E74102400075741503631304E104200033030301054000800060050F2040001101100075741503631304E100800020086
                    IE: WPA Version 1
                        Group Cipher : TKIP
                        Pairwise Ciphers (2) : CCMP TKIP
                        Authentication Suites (1) : PSK
                    Encryption key:on
                    Bit Rates:1 Mb/s; 2 Mb/s; 5.5 Mb/s; 11 Mb/s; 6 Mb/s
                              9 Mb/s; 12 Mb/s; 18 Mb/s; 24 Mb/s; 36 Mb/s
                              48 Mb/s; 54 Mb/s
